#!/bin/sh
###############################################################################
# NAME:		    popcorn
#
# AUTHOR:	    Ethan D. Twardy <edtwardy@mtu.edu>
#
# DESCRIPTION:	    This script implements some basic commands for interacting
#		    with the kernel-factory image.
#
# CREATED:	    09/12/2018
#
# LAST EDITED:	    09/17/2018
###

go() {
    containerName=`docker ps -a | grep 'kernel-factory' | awk '{print $NF;}'`
    if [ "x$containerName" = "x" ]; then
	echo >&2 "The container is not running."
	return 1
    fi

    # Start the container
    docker start $containerName
    if [ $? != "0" ]; then
	return 1
    fi

    response=`docker port $containerName 22`
    hostPort=`echo $response | awk -F':' '{print $2;}'`
    hostIp=`echo $response | awk -F':' '{print $1;}'`
    ssh -o "StrictHostKeyChecking no" root@${hostIp} -p $hostPort

    # Stop the container
    docker stop $containerName
}

stop() {
    containerName=`docker ps -a | grep 'kernel-factory' | awk '{print $NF;}'`
    if [ "x$containerName" = "x" ]; then
	echo >&2 "The container is not running."
	return 1
    fi

    docker container stop $containerName
}

read -r -d '' USAGE <<EOF
\nUsage: popcorn COMMAND
A convenience for interacting with the kernel-factory container.

go\tConnect to the kernel-factory container through ssh.
stop\tHalt the container using docker.\n
EOF

case $1 in
    go)
	go
	;;
    stop)
	stop
	;;
    *)
	echo "$USAGE"
	false
	;;
esac

##############################################################################
